/** KERNEL PANIC: two antivirus daemons purge corrupted processes inside a crashing server (plan section 2). */
import type { ThemeDef } from '../contracts/theme';

export const KERNEL_PANIC: ThemeDef = {
  id: 'kernelPanic',
  title: 'KERNEL PANIC',
  tagline: 'Purge the corrupted processes before the kernel panics.',
  names: {
    runCurrency: 'Bits',
    metaCurrency: 'Cores',
    shop: 'Patch Bay',
    meta: 'Firmware',
    lives: 'Spare Kernels',
    wave: 'Cycle',
    sector: 'Sector',
    vehicles: { lancer: 'LANCER', bulwark: 'BULWARK', specter: 'SPECTER', tinker: 'TINKER' },
    vehicleBlurbs: {
      lancer: 'Balanced daemon. Twin blaster.',
      bulwark: 'Heavy daemon. Spread cannon, ram dash, -20% contact damage.',
      specter: 'Glass cannon. Needle gun with pierce, 2 dash charges.',
      tinker: 'Support. Chaining arc pistol, healing drone.',
    },
    specials: {
      railburst: 'RAILBURST',
      firewall: 'FIREWALL',
      blinkSwarm: 'BLINK SWARM',
      patchDrone: 'PATCH DRONE',
    },
    enemies: {
      shard: 'SHARD',
      dart: 'DART',
      fork: 'FORK',
      spiker: 'SPIKER',
      warden: 'WARDEN',
      leech: 'LEECH',
    },
    bosses: { forkBomb: 'FORK BOMB', raceCondition: 'RACE CONDITION', kernel: 'THE KERNEL' },
    teamItems: {
      spareKernel: 'Spare Kernel',
      linkAmp: 'Link Amplifier',
      linkRange: 'Link Range',
      reviveProtocol: 'Revive Protocol',
    },
    extract: 'EXTRACT',
    pushDeeper: 'PUSH DEEPER',
    overflow: 'OVERFLOW',
    versus: 'VERSUS',
    coop: 'CO-OP',
  },
  palette: {
    p1: 0x19e6ff,
    p2: 0xff3fd0,
    p2Colorblind: 0xff9a1f,
    enemyShot: 0xff5a1f,
    enemyShotCore: 0xffd08a,
    pickup: 0x7dff9a,
    link: 0x9d7bff,
    ui: { bg: 0x05060d, panel: 0x0c1022, text: 0xe6f6ff, dim: 0x6a7a99 },
    sectors: [
      {
        floor: 0x04070f,
        grid: 0x1a6cff,
        accent: 0x19e6ff,
        sky: 0x070b1e,
        fog: 0x050814,
        enemy: 0x46ff9e,
        elite: 0xff2d55,
      },
      {
        floor: 0x0a0510,
        grid: 0x8a2cff,
        accent: 0xc05cff,
        sky: 0x12061e,
        fog: 0x0b0614,
        enemy: 0xffe14a,
        elite: 0xff2d55,
      },
      {
        floor: 0x100406,
        grid: 0xff2d4a,
        accent: 0xff7a3a,
        sky: 0x1a0508,
        fog: 0x120508,
        enemy: 0xff9df2,
        elite: 0x39ffec,
      },
    ],
  },
  geometry: { enemyFamily: 'platonic', hullStyle: 'sled', emissiveMask: 'edges', edgeWidth: 0.045 },
  shading: {
    floorMode: 'GRID',
    skyMode: 'NEBULA_GLYPHS',
    fogDensity: 0.012,
    heatShimmer: 0,
    minEmissive: 0.15,
    bloomStrength: 0.9,
    bloomThreshold: 0.8,
  },
  audio: {
    bpm: 112,
    rootMidi: 57,
    mode: 'aeolian',
    progression: [0, 8, 3, 10],
    sectorKeyShift: [0, 3, 7],
    bossKeyShift: 1,
    timbre: 'synthwave',
  },
};
